param(
    [string]$Command = "interactive",
    [switch]$NoAutoSummary  # Skip auto-summarization
)

# Session names database
$NamesFile = "$env:USERPROFILE\.claude\session-names.json"
$ProjectsDir = "$env:USERPROFILE\.claude\projects"
$ClaudeExe = "$env:USERPROFILE\.bun\bin\claude.exe"

# Global: Track duplicate files for cleanup
$script:duplicateFiles = @()

# Load session names (convert PSCustomObject to hashtable for dynamic property addition)
function Get-SessionNames {
    if (Test-Path $NamesFile) {
        try {
            $content = Get-Content $NamesFile -Raw -Encoding UTF8 -ErrorAction Stop
            $json = $content | ConvertFrom-Json -ErrorAction Stop

            # Convert sessions PSCustomObject to hashtable
            $sessionsHash = @{}
            if ($json.sessions) {
                $json.sessions.PSObject.Properties | ForEach-Object {
                    $sessionsHash[$_.Name] = @{
                        name = $_.Value.name
                        updatedAt = $_.Value.updatedAt
                        type = $_.Value.type
                    }
                }
            }
            return @{ sessions = $sessionsHash }
        }
        catch {
            return @{ sessions = @{} }
        }
    }
    return @{ sessions = @{} }
}

# Save session names
function Save-SessionNames {
    param($names)
    $names | ConvertTo-Json -Depth 10 | Set-Content $NamesFile -Encoding UTF8
}

# Get display name for session
function Get-SessionDisplayName {
    param($sessionId, $defaultSummary, $names)

    $sessionData = $names.sessions.$sessionId
    if ($sessionData -and $sessionData.name) {
        return $sessionData.name
    }
    return $defaultSummary
}

# Extract meaningful session title from conversation rallies (no API call - instant)
function Get-QuickTitle {
    param($filePath)

    # Read first 30 lines (fast) + last 50 lines (need to seek)
    $firstLines = @()
    $lastLines = @()
    
    try {
        # First 30 lines - fast
        $firstLines = Get-Content $filePath -TotalCount 30 -Encoding UTF8 -ErrorAction Stop
        
        # Last 50 lines - use tail-like approach for large files
        $fileInfo = Get-Item $filePath
        if ($fileInfo.Length -gt 50KB) {
            # File > 50KB: read last 50KB and extract lines
            $stream = [System.IO.File]::Open($filePath, [System.IO.FileMode]::Open, [System.IO.FileAccess]::Read, [System.IO.FileShare]::ReadWrite)
            $seekPos = [Math]::Max(0, $stream.Length - 50KB)
            $stream.Seek($seekPos, [System.IO.SeekOrigin]::Begin) | Out-Null
            $reader = New-Object System.IO.StreamReader($stream, [System.Text.Encoding]::UTF8)
            $tailContent = $reader.ReadToEnd()
            $reader.Close()
            $stream.Close()
            $lastLines = ($tailContent -split "`n") | Select-Object -Last 50
        } else {
            # Small file: read all and take last 50
            $allContent = Get-Content $filePath -Encoding UTF8 -ErrorAction Stop
            $lastLines = $allContent | Select-Object -Last 50
        }
    }
    catch {
        try {
            $firstLines = Get-Content $filePath -TotalCount 30 -ErrorAction SilentlyContinue
            $lastLines = $firstLines
        }
        catch { return $null }
    }
    
    if (-not $lastLines -or $lastLines.Count -eq 0) { return $null }
    $allLines = $lastLines

    # Helper: Check if text is meaningful as a title
    function Test-MeaningfulTitle {
        param($text)
        if (-not $text -or $text.Length -lt 8) { return $false }

        # Skip patterns - not meaningful as titles
        $skipPatterns = @(
            # Status/completion
            "^(完了|了解|承知|はい|OK|おっけ|報告|確認|修正|対応|実行|テスト完了|チェック)",
            "^(Done|Fixed|Completed|OK|Sure|Yes|No|Got it|Thanks|Thank you)",
            # Greetings/conversational
            "^(Hi|Hello|そうだね|なるほど|いいね|ありがと|お疲れ|よし|では|test|テスト$)",
            # System/error messages
            "^(Caveat|Generated by|Note:|Warning:|Error:|Invalid|Please run|Failed)",
            "(API key|api key|apikey|token expired|unauthorized|forbidden)",
            # URLs
            "^https?://",
            # Just emojis or markers
            "^[✅📊🔥🎯💡🚨⚠️]",
            # Just headers without context
            "^(導入済み|実装した|完成した|インストールした|レビュー結果|サマリー)",
            # Dates/times only
            "^\d{4}年\d{1,2}月\d{1,2}日",
            "^\d{1,2}/\d{1,2}/\d{4}",
            # Code/commands
            "^(```|import |const |var |let |function |class |def |npm |pip |git |cd |ls )",
            "^[A-Z_]+\s*=",  # ENV vars
            # File paths
            "^(C:\\|/Users/|~/|\./|http)",
            # Questions that are too generic
            "^(確認していい|これでいい|どう思う|何か|ある？)$",
            "^This session is being continued",
            "^<user-prompt-submit-hook>",
            "^Claude Auto-Mode loaded",
            "^<system-reminder>",
            "^(Summarize this|Create a short title)",
            "^(Focus on the main|Output ONLY the title|The conversation is summarized)",
            "^(Just output the summary|Example outputs:|Initial Context)",
            "(Summarize this Claude Code session|5-10 words)",
            "^\d+\] \[ERROR\]",
            "^(Session content:|Session ID:)",
            "\.com/[a-zA-Z]",
            "/status/\d+",
            "^claude\\\\projects\\\\",
            "^jsonl",
            "permission_mode",
            "^@\{",
            "^<task-notification>",
            "^Initial Request:",
            "^dev/tenormusica/",
            "^com/[A-Za-z]",
            "^<output",
            "^The task was to",
            "^output<",
            "^md.+with a new",
            "^</summary>",
            "^Skill Definition:",
            "_monitor_service$",
            "^Read the output",
            "claude\\\\skills\\\\",
            "claude.skills.",
            "^py ",
            "^File Reading:",
            "^- First attempted",
            "^Web Searches Performed:",
            "5-20",
            "^File Edits:",
            "[\uFF61-\uFF9F]",
            "^S \{",
            '^"session_id":',
            "session_id",
            "^セッション終了を検知",
            "^Is this a meaningful session title",
            "^Archive Creation:",
            "^md``",
            "^Error Encountered:"
        )

        foreach ($pattern in $skipPatterns) {
            if ($text -match $pattern) { return $false }
        }

        # Skip if contains file extensions (likely a file reference)
        if ($text -match "\.(png|jpg|jpeg|gif|md|ps1|json|txt|ts|js|py)") { return $false }

        # Skip if garbled (>1/3 unusual chars)
        # Also skip if contains Shift-JIS mojibake patterns (half-width katakana)
        $cleanChars = ($text -replace "[a-zA-Z0-9\u3040-\u30FF\u4E00-\u9FFF\s\-\.\,\!\?\(\)\:：、。「」]", "")
        if ($cleanChars.Length -gt ($text.Length / 3)) { return $false }

        # Skip if mostly punctuation/symbols
        if (($text -replace "[\w\u3040-\u30FF\u4E00-\u9FFF]", "").Length -gt ($text.Length / 2)) { return $false }

        return $true
    }

    # Helper: Extract clean text from message content
    function Get-CleanText {
        param($content)
        if (-not $content) { return $null }

        $text = $content -replace "`n", " " -replace "`r", "" -replace "\s+", " "
        $text = $text.Trim()

        # Remove markdown formatting
        $text = $text -replace '\*\*(.+?)\*\*', '$1'  # bold
        $text = $text -replace '```[\s\S]*?```', ''  # code blocks
        $text = $text -replace '^\s*[-*]\s*', ''  # list markers
        $text = $text -replace '^#+\s*', ''  # headers

        return $text.Trim()
    }

    # Collect all messages in order (newest first)
    $messages = @()
    foreach ($line in $allLines) {
        try {
            $entry = $line | ConvertFrom-Json -ErrorAction SilentlyContinue
            if ($entry.message -and $entry.message.role -and $entry.message.content) {
                $content = if ($entry.message.content -is [array]) {
                    ($entry.message.content | Where-Object { $_.type -eq "text" } | Select-Object -First 1).text
                } else { $entry.message.content }

                if ($content -and $content.Length -gt 5) {
                    $messages += @{
                        role = $entry.message.role
                        content = $content
                    }
                }
            }
        }
        catch { }
    }

    # Reverse to get newest first
    [array]::Reverse($messages)

    # Strategy 1: Look for topic description in recent USER messages
    # (What did the user ask for? That's usually the best title)
    $userCount = 0
    foreach ($msg in $messages) {
        if ($msg.role -ne "user") { continue }
        $userCount++
        if ($userCount -gt 15) { break }  # Check up to 15 recent user messages

        $text = Get-CleanText -content $msg.content

        # Take first meaningful sentence
        $sentences = $text -split "[。\.\!\?]" | Where-Object { $_.Trim().Length -gt 5 }
        foreach ($sentence in $sentences) {
            $sentence = $sentence.Trim()
            if ($sentence.Length -gt 55) {
                $sentence = $sentence.Substring(0, 55)
                $lastSpace = $sentence.LastIndexOf(" ")
                if ($lastSpace -gt 35) { $sentence = $sentence.Substring(0, $lastSpace) }
                $sentence = $sentence + "..."
            }

            if (Test-MeaningfulTitle -text $sentence) {
                return $sentence
            }
        }
    }

    # Strategy 2: Look for descriptive headers in assistant responses
    foreach ($msg in $messages) {
        if ($msg.role -ne "assistant") { continue }

        # Look for meaningful headers (## Something specific)
        if ($msg.content -match "##\s+([^#\n]+)") {
            $header = $matches[1].Trim()
            # Remove emojis from start
            $header = $header -replace "^[✅📊🔥🎯💡🚨⚠️\s]+", ""
            if ($header.Length -gt 5 -and $header.Length -lt 50) {
                if (Test-MeaningfulTitle -text $header) {
                    return $header
                }
            }
        }
    }

    # Strategy 3: First user message as last resort
    foreach ($line in $allLines | Select-Object -First 20) {
        try {
            $entry = $line | ConvertFrom-Json -ErrorAction SilentlyContinue
            if ($entry.message -and $entry.message.role -eq "user" -and $entry.message.content) {
                $text = Get-CleanText -content $entry.message.content
                if ($text.Length -gt 55) {
                    $text = $text.Substring(0, 55) + "..."
                }
                if (Test-MeaningfulTitle -text $text) {
                    return $text
                }
            }
        }
        catch { }
    }

    return $null
}

# Generate AI summary for a session (used by manual S key only)
function Get-AISummaryQuiet {
    param($sessionId, $filePath)

    # Extract user messages
    $lines = Get-Content $filePath -TotalCount 50 -Encoding UTF8 -ErrorAction SilentlyContinue
    $userMessages = @()
    foreach ($line in $lines) {
        try {
            $entry = $line | ConvertFrom-Json -ErrorAction SilentlyContinue
            if ($entry.message -and $entry.message.role -eq "user" -and $entry.message.content) {
                $content = $entry.message.content
                if ($content -is [string] -and $content.Length -gt 0) {
                    $userMessages += $content
                }
            }
        }
        catch { }
    }

    if ($userMessages.Count -eq 0) {
        return $null
    }

    # Create prompt for summarization - strict title-only format
    $messagesText = ($userMessages | Select-Object -First 3) -join " | "
    if ($messagesText.Length -gt 500) {
        $messagesText = $messagesText.Substring(0, 500)
    }

    # Japanese prompt for better readability
    $prompt = "このコーディングセッションの短いタイトルを日本語で作成して。5-20文字程度で、何をやってるか一目でわかるように。タイトルのみ出力、説明不要。例：'GitHub Actions設定' 'Reactコンポーネント修正' 'SE通知hookデバッグ' 'Firebase認証実装'。セッション内容: $messagesText"

    try {
        $env:ANTHROPIC_API_KEY = ""
        $result = & $ClaudeExe -p $prompt --model haiku --dangerously-skip-permissions 2>$null
        if ($result) {
            $summary = ($result -split "`n")[0].Trim().Trim('"').Trim("'")
            if ($summary.Length -gt 55) {
                $summary = $summary.Substring(0, 55)
            }
            if ($summary.Length -gt 5 -and -not ($summary -match "^(I |This |The |Here |Let me|Sorry|申し訳|ただいま)")) {
                return $summary
            }
        }
    }
    catch { }

    return $null
}

# AI-based title validation and generation (called during session list build)
function Get-ValidatedTitle {
    param($filePath, $quickTitle)
    
    $ClaudeExe = "$env:USERPROFILE\.bun\bin\claude.exe"
    
    # If no quick title, generate from scratch
    if (-not $quickTitle -or $quickTitle -eq "(no content)") {
        return Get-AIGeneratedTitle -filePath $filePath
    }
    
    # Validate if quick title is meaningful using AI
    $validationPrompt = "Is this a meaningful session title that describes what work was done? Answer only YES or NO. Title: `"$quickTitle`""
    
    try {
        $env:ANTHROPIC_API_KEY = ""
        $result = & $ClaudeExe -p $validationPrompt --model haiku --dangerously-skip-permissions 2>$null
        $answer = ($result -split "`n")[0].Trim().ToUpper()
        
        if ($answer -match "^YES") {
            return $quickTitle
        }
        
        # Title rejected, generate new one
        return Get-AIGeneratedTitle -filePath $filePath
    }
    catch {
        # On error, return quick title as fallback
        return $quickTitle
    }
}

# Generate title from session content using AI (reads latest + first messages)
function Get-AIGeneratedTitle {
    param($filePath)
    
    $ClaudeExe = "$env:USERPROFILE\.bun\bin\claude.exe"
    
    # Extract messages from latest content (priority) + first content (fallback)
    $userMessages = @()
    
    try {
        $fileInfo = Get-Item $filePath
        
        # Read last 50KB for latest messages
        if ($fileInfo.Length -gt 50KB) {
            $stream = [System.IO.File]::Open($filePath, [System.IO.FileMode]::Open, [System.IO.FileAccess]::Read, [System.IO.FileShare]::ReadWrite)
            $seekPos = [Math]::Max(0, $stream.Length - 50KB)
            $stream.Seek($seekPos, [System.IO.SeekOrigin]::Begin) | Out-Null
            $reader = New-Object System.IO.StreamReader($stream, [System.Text.Encoding]::UTF8)
            $tailContent = $reader.ReadToEnd()
            $reader.Close()
            $stream.Close()
            $lastLines = ($tailContent -split "`n") | Select-Object -Last 30
        } else {
            $lastLines = Get-Content $filePath -Encoding UTF8 -ErrorAction SilentlyContinue | Select-Object -Last 30
        }
        
        # Extract user messages from latest content
        foreach ($line in $lastLines) {
            try {
                $entry = $line | ConvertFrom-Json -ErrorAction SilentlyContinue
                if ($entry.message -and $entry.message.role -eq "user" -and $entry.message.content) {
                    $content = $entry.message.content
                    if ($content -is [string] -and $content.Length -gt 10 -and $content.Length -lt 500) {
                        $userMessages += $content
                        if ($userMessages.Count -ge 2) { break }
                    }
                }
            }
            catch { }
        }
        
        # If no good messages from latest, try first 20 lines
        if ($userMessages.Count -eq 0) {
            $firstLines = Get-Content $filePath -TotalCount 20 -Encoding UTF8 -ErrorAction SilentlyContinue
            foreach ($line in $firstLines) {
                try {
                    $entry = $line | ConvertFrom-Json -ErrorAction SilentlyContinue
                    if ($entry.message -and $entry.message.role -eq "user" -and $entry.message.content) {
                        $content = $entry.message.content
                        if ($content -is [string] -and $content.Length -gt 10 -and $content.Length -lt 500) {
                            $userMessages += $content
                            if ($userMessages.Count -ge 2) { break }
                        }
                    }
                }
                catch { }
            }
        }
    }
    catch { }
    
    if ($userMessages.Count -eq 0) {
        return "(no content)"
    }
    
    $messagesText = ($userMessages -join " | ")
    if ($messagesText.Length -gt 400) {
        $messagesText = $messagesText.Substring(0, 400)
    }
    
    $prompt = "Create a short title (10-30 chars) in Japanese describing what this coding session is about. Output ONLY the title, no explanation. Session content: $messagesText"
    
    try {
        $env:ANTHROPIC_API_KEY = ""
        $result = & $ClaudeExe -p $prompt --model haiku --dangerously-skip-permissions 2>$null
        if ($result) {
            $title = ($result -split "`n")[0].Trim().Trim('"').Trim("'")
            if ($title.Length -gt 50) { $title = $title.Substring(0, 50) }
            if ($title.Length -gt 3 -and -not ($title -match "^(I |This |The |Here |Sorry)")) {
                return $title
            }
        }
    }
    catch { }
    
    return "(no content)"
}


# Parallel AI title generation for multiple sessions (fast)
function Get-AITitlesParallel {
    param($sessionInfos)  # Array of @{Index; FilePath; Prompt}
    
    if ($sessionInfos.Count -eq 0) { return @{} }
    
    $ClaudeExe = "$env:USERPROFILE\.bun\bin\claude.exe"
    $results = @{}
    
    # Start all jobs in parallel
    $jobs = @()
    foreach ($info in $sessionInfos) {
        $job = Start-Job -ScriptBlock {
            param($exe, $prompt, $idx)
            [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
            $env:ANTHROPIC_API_KEY = ""
            $result = & $exe -p $prompt --model haiku --dangerously-skip-permissions 2>$null
            # Return as Base64 to avoid encoding issues, with index prefix
            $encoded = [Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes($result))
            "$idx|$encoded"
        } -ArgumentList $ClaudeExe, $info.Prompt, $info.Index
        $jobs += $job
    }
    
    # Wait for all jobs (max 30 seconds)
    $completed = $jobs | Wait-Job -Timeout 30
    $rawResults = $completed | Receive-Job
    $jobs | Remove-Job -Force
    
    # Parse results
    foreach ($raw in $rawResults) {
        if ($raw -match "^(\d+)\|(.+)$") {
            $idx = [int]$matches[1]
            $encoded = $matches[2]
            try {
                $decoded = [System.Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($encoded))
                $title = ($decoded -split "`n")[0].Trim().Trim('"').Trim("'")
                if ($title.Length -gt 50) { $title = $title.Substring(0, 50) }
                if ($title.Length -gt 3 -and -not ($title -match "^(I |This |The |Here |Sorry)")) {
                    $results[$idx] = $title
                }
            }
            catch { }
        }
    }
    
    return $results
}

# Generate AI summary (verbose mode for manual trigger)
function Get-AISummary {
    param($sessionId, $filePath)

    Write-Host ""
    Write-Host "Generating AI summary (Haiku)..." -ForegroundColor Yellow

    $summary = Get-AISummaryQuiet -sessionId $sessionId -filePath $filePath

    if ($summary) {
        Write-Host "Summary: $summary" -ForegroundColor Green
    }
    else {
        Write-Host "Failed to generate summary" -ForegroundColor Red
    }

    return $summary
}

# Cleanup duplicate session files
function Remove-DuplicateFiles {
    param($duplicates)

    if ($duplicates.Count -eq 0) {
        Write-Host "No duplicate files to clean up." -ForegroundColor Yellow
        return 0
    }

    Write-Host ""
    Write-Host "Found $($duplicates.Count) duplicate files to remove:" -ForegroundColor Yellow
    foreach ($file in $duplicates) {
        Write-Host "  - $($file.Name) ($(($file.LastWriteTime).ToString('yyyy-MM-dd HH:mm')))" -ForegroundColor Gray
    }

    Write-Host ""
    Write-Host "Delete these files? [Y/N]: " -NoNewline -ForegroundColor Cyan
    $confirm = Read-Host

    if ($confirm -match "^[Yy]") {
        $deleted = 0
        foreach ($file in $duplicates) {
            try {
                Remove-Item $file.FullName -Force -ErrorAction Stop
                $deleted++
            }
            catch {
                Write-Host "  Failed to delete: $($file.Name)" -ForegroundColor Red
            }
        }
        Write-Host "Deleted $deleted files." -ForegroundColor Green
        return $deleted
    }
    else {
        Write-Host "Cancelled." -ForegroundColor Yellow
        return 0
    }
}

Write-Host "=== Claude Session Manager ===" -ForegroundColor Cyan

# Load names database
$sessionNames = Get-SessionNames

# Get sessions
Write-Host "Scanning sessions..."
$allSessions = @()

$projectDirs = Get-ChildItem -Path $ProjectsDir -Directory -ErrorAction SilentlyContinue
Write-Host "Found $($projectDirs.Count) project dirs"

foreach ($projectDir in $projectDirs) {
    $jsonFiles = Get-ChildItem -Path $projectDir.FullName -Filter "*.jsonl" -ErrorAction SilentlyContinue |
                 Sort-Object LastWriteTime -Descending

    foreach ($jsonFile in $jsonFiles) {
        try {
            $firstLine = Get-Content $jsonFile.FullName -TotalCount 1 -Encoding UTF8 -ErrorAction Stop
            if (-not $firstLine) { continue }

            $data = $firstLine | ConvertFrom-Json -ErrorAction Stop

            # Skip compact_boundary files (session continuation markers)
            if ($data.type -eq "system" -and $data.subtype -eq "compact_boundary") {
                continue
            }

            # Get session ID (from first line or filename for compacted sessions)
            $sessionId = $null
            if ($data.sessionId) {
                $sessionId = $data.sessionId
            } else {
                $sessionId = [System.IO.Path]::GetFileNameWithoutExtension($jsonFile.Name)
            }
            if (-not $sessionId) { continue }

            # Get default summary - prefer compacted session summary first
            $defaultSummary = $null
            if ($data.type -eq "summary" -and $data.summary) {
                $len = [Math]::Min(50, $data.summary.Length)
                $defaultSummary = $data.summary.Substring(0, $len)
            }
            if (-not $defaultSummary) {
                $defaultSummary = Get-QuickTitle -filePath $jsonFile.FullName
            }
            if (-not $defaultSummary) {
                $defaultSummary = "(no content)"
            }
            # Skip warmup, empty, and AI prompt sessions
            if ($defaultSummary -match "^(no content|Warmup|\(no content\)|Create a short title|このコーディングセッション)") {
                continue
            }

            # Skip very small sessions (likely warmup or AI prompt sessions)
            if ($jsonFile.Length -lt 5000) {
                continue
            }

            # Skip AI skill session directories
            if ($projectDir.Name -match "(ai-buzz-extractor|claude-skills-test|note-auto-article)") {
                continue
            }

            # Get display name (custom name or default)
            $displayName = Get-SessionDisplayName -sessionId $sessionId -defaultSummary $defaultSummary -names $sessionNames

            # Check if has custom name
            $hasCustomName = $false
            if ($sessionNames.sessions.$sessionId -and $sessionNames.sessions.$sessionId.name) {
                $hasCustomName = $true
            }

            $allSessions += [PSCustomObject]@{
                SessionId = $sessionId
                Summary = $displayName
                DefaultSummary = $defaultSummary
                LastModified = $jsonFile.LastWriteTime
                HasCustomName = $hasCustomName
                FilePath = $jsonFile.FullName
                FileInfo = $jsonFile
            }
        }
        catch {
            # Skip errors
        }
    }
}

# Proper deduplication by SessionId - keep only the most recent
$grouped = $allSessions | Group-Object SessionId
$sessions = @()
$script:duplicateFiles = @()

foreach ($group in $grouped) {
    $sorted = $group.Group | Sort-Object LastModified -Descending
    # Keep the newest
    $sessions += $sorted[0]
    # Track older duplicates for potential cleanup
    if ($sorted.Count -gt 1) {
        $script:duplicateFiles += $sorted[1..($sorted.Count-1)] | ForEach-Object { $_.FileInfo }
    }
}

# Sort final list by LastModified
$sessions = $sessions | Sort-Object LastModified -Descending

# AI title regeneration for clearly bad titles (parallel, max 5)
$maxValidate = [Math]::Min(15, $sessions.Count)
$badSessions = @()

for ($i = 0; $i -lt $maxValidate; $i++) {
    $session = $sessions[$i]
    if ($session.HasCustomName) { continue }
    
    $title = $session.Summary
    $needsAI = $false
    
    # Check for clearly bad titles
    if (-not $title -or $title -eq "(no content)") { $needsAI = $true }
    elseif ($title.Length -lt 8) { $needsAI = $true }
    elseif ($title -match "^(Base directory|Error Encountered|Final Notification|skill:|Skill Definition)") { $needsAI = $true }
    elseif ($title -match "^\[Request interrupted") { $needsAI = $true }
    
    if ($needsAI -and $badSessions.Count -lt 5) {
        # Extract messages for prompt (read last 30KB for latest content)
        $messagesText = ""
        try {
            $fileInfo = Get-Item $session.FilePath
            $lines = @()
            
            if ($fileInfo.Length -gt 30KB) {
                # Large file: read last 30KB
                $stream = [System.IO.File]::Open($session.FilePath, [System.IO.FileMode]::Open, [System.IO.FileAccess]::Read, [System.IO.FileShare]::ReadWrite)
                $seekPos = [Math]::Max(0, $stream.Length - 30KB)
                $stream.Seek($seekPos, [System.IO.SeekOrigin]::Begin) | Out-Null
                $reader = New-Object System.IO.StreamReader($stream, [System.Text.Encoding]::UTF8)
                $tailContent = $reader.ReadToEnd()
                $reader.Close()
                $stream.Close()
                $lines = ($tailContent -split "`n") | Select-Object -Last 30
            } else {
                # Small file: read all and take last 30
                $allLines = Get-Content $session.FilePath -Encoding UTF8 -ErrorAction SilentlyContinue
                $lines = $allLines | Select-Object -Last 30
            }
            
            foreach ($line in $lines) {
                try {
                    $entry = $line | ConvertFrom-Json -ErrorAction SilentlyContinue
                    if ($entry.isMeta) { continue }
                    if ($entry.message -and $entry.message.content) {
                        $role = $entry.message.role
                        $content = $entry.message.content
                        $textContent = ""
                        if ($content -is [string]) {
                            if ($content -notmatch "tool_result|tool_use_id") {
                                $textContent = $content
                            }
                        } elseif ($content -is [array]) {
                            foreach ($item in $content) {
                                if ($item.type -eq "text" -and $item.text -and $item.text.Length -gt 10) {
                                    if ($item.text -notmatch "^Base directory for|ARGUMENTS:") {
                                        $textContent = $item.text
                                        break
                                    }
                                }
                            }
                        }
                        if ($textContent.Length -gt 10 -and $textContent.Length -lt 500) {
                            $messagesText += " $textContent"
                            if ($messagesText.Length -gt 400) { break }
                        }
                    }
                }
                catch { }
            }
        }
        catch { }
        
        if ($messagesText.Length -gt 10) {
            if ($messagesText.Length -gt 300) { $messagesText = $messagesText.Substring(0, 300) }
            $prompt = "Create a short title (10-30 chars) in Japanese describing this coding session. Output ONLY the title. Content: $messagesText"
            $badSessions += @{ Index = $i; FilePath = $session.FilePath; Prompt = $prompt }
        } else {
        }
    }
}

if ($badSessions.Count -gt 0) {
    Write-Host "  Generating AI titles for $($badSessions.Count) sessions (parallel)..." -ForegroundColor Yellow
    $aiTitles = Get-AITitlesParallel -sessionInfos $badSessions
    foreach ($idx in $aiTitles.Keys) {
        $sessions[$idx].Summary = $aiTitles[$idx]
        Write-Host "  -> Session $idx`: $($aiTitles[$idx])" -ForegroundColor Cyan
    }
}

$duplicateCount = $script:duplicateFiles.Count
if ($duplicateCount -gt 0) {
    Write-Host "Found $($sessions.Count) unique sessions ($duplicateCount duplicates detected)" -ForegroundColor Green
}
else {
    Write-Host "Found $($sessions.Count) sessions" -ForegroundColor Green
}

# Note: Auto-titling disabled for fast startup
# Stop hook handles automatic naming after each response
# Use S key to manually summarize unnamed sessions

if ($Command -eq "interactive" -and $sessions.Count -gt 0) {
    $selectedIndex = 0
    $maxDisplay = [Math]::Min(15, $sessions.Count)

    while ($true) {
        Clear-Host
        Write-Host "=== Claude Session Manager ===" -ForegroundColor Cyan
        if ($script:duplicateFiles.Count -gt 0) {
            Write-Host "($($script:duplicateFiles.Count) duplicate files - press D to clean up)" -ForegroundColor DarkYellow
        }
        Write-Host ""

        for ($i = 0; $i -lt $maxDisplay; $i++) {
            $session = $sessions[$i]
            $marker = if ($i -eq $selectedIndex) { "> " } else { "  " }
            $color = if ($i -eq $selectedIndex) { "Green" } else { "White" }

            # Add star for custom named sessions
            $star = if ($session.HasCustomName) { "*" } else { " " }

            $display = "$marker$star[$($i+1)] $($session.Summary)"
            if ($display.Length -gt 70) { $display = $display.Substring(0, 70) + "..." }

            Write-Host $display -ForegroundColor $color
        }

        Write-Host ""
        $helpText = "[Up/Down] Move  [Enter] Resume  [S] Re-summarize  [N] Name"
        if ($script:duplicateFiles.Count -gt 0) {
            $helpText += "  [D] Clean duplicates"
        }
        $helpText += "  [Q] Quit"
        Write-Host $helpText -ForegroundColor Gray

        $key = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")

        switch ($key.VirtualKeyCode) {
            38 { if ($selectedIndex -gt 0) { $selectedIndex-- } }  # Up
            40 { if ($selectedIndex -lt $maxDisplay - 1) { $selectedIndex++ } }  # Down
            13 {  # Enter - Resume
                $selected = $sessions[$selectedIndex]
                Write-Host ""
                Write-Host "Resuming session: $($selected.SessionId)" -ForegroundColor Green
                & $ClaudeExe -r $selected.SessionId
                return
            }
            83 {  # S - Re-summarize
                $selected = $sessions[$selectedIndex]
                $summary = Get-AISummary -sessionId $selected.SessionId -filePath $selected.FilePath
                if ($summary) {
                    if (-not $sessionNames.sessions) {
                        $sessionNames.sessions = @{}
                    }
                    $sessionNames.sessions.($selected.SessionId) = @{
                        name = $summary
                        updatedAt = (Get-Date).ToString("yyyy-MM-ddTHH:mm:ss")
                        type = "ai"
                    }
                    Save-SessionNames -names $sessionNames
                    $sessions[$selectedIndex].Summary = $summary
                    $sessions[$selectedIndex].HasCustomName = $true
                    Write-Host "Saved! Press any key..." -ForegroundColor Green
                    $null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
                }
                else {
                    Write-Host "Press any key to continue..." -ForegroundColor Yellow
                    $null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
                }
            }
            78 {  # N - Manual Name
                $selected = $sessions[$selectedIndex]
                Write-Host ""
                Write-Host "Current: $($selected.Summary)" -ForegroundColor Yellow
                Write-Host "Enter new name (empty to cancel): " -NoNewline -ForegroundColor Cyan
                $newName = Read-Host

                if ($newName -and $newName.Trim().Length -gt 0) {
                    $newName = $newName.Trim()
                    if ($newName.Length -gt 50) {
                        $newName = $newName.Substring(0, 50)
                    }
                    if (-not $sessionNames.sessions) {
                        $sessionNames.sessions = @{}
                    }
                    $sessionNames.sessions.($selected.SessionId) = @{
                        name = $newName
                        updatedAt = (Get-Date).ToString("yyyy-MM-ddTHH:mm:ss")
                        type = "manual"
                    }
                    Save-SessionNames -names $sessionNames
                    $sessions[$selectedIndex].Summary = $newName
                    $sessions[$selectedIndex].HasCustomName = $true
                    Write-Host "Saved!" -ForegroundColor Green
                    Start-Sleep -Milliseconds 500
                }
            }
            68 {  # D - Clean duplicates
                if ($script:duplicateFiles.Count -gt 0) {
                    $deleted = Remove-DuplicateFiles -duplicates $script:duplicateFiles
                    if ($deleted -gt 0) {
                        $script:duplicateFiles = @()
                    }
                    Write-Host "Press any key to continue..." -ForegroundColor Gray
                    $null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
                }
            }
            81 { return }  # Q
            default {
                $char = $key.Character.ToString().ToLower()
                if ($char -eq 'q') { return }
                if ($char -eq 'd' -and $script:duplicateFiles.Count -gt 0) {
                    $deleted = Remove-DuplicateFiles -duplicates $script:duplicateFiles
                    if ($deleted -gt 0) {
                        $script:duplicateFiles = @()
                    }
                    Write-Host "Press any key to continue..." -ForegroundColor Gray
                    $null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
                }
                if ($char -eq 's') {
                    $selected = $sessions[$selectedIndex]
                    $summary = Get-AISummary -sessionId $selected.SessionId -filePath $selected.FilePath
                    if ($summary) {
                        if (-not $sessionNames.sessions) {
                            $sessionNames.sessions = @{}
                        }
                        $sessionNames.sessions.($selected.SessionId) = @{
                            name = $summary
                            updatedAt = (Get-Date).ToString("yyyy-MM-ddTHH:mm:ss")
                            type = "ai"
                        }
                        Save-SessionNames -names $sessionNames
                        $sessions[$selectedIndex].Summary = $summary
                        $sessions[$selectedIndex].HasCustomName = $true
                        Write-Host "Saved! Press any key..." -ForegroundColor Green
                        $null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
                    }
                    else {
                        Write-Host "Press any key to continue..." -ForegroundColor Yellow
                        $null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
                    }
                }
                if ($char -eq 'n') {
                    $selected = $sessions[$selectedIndex]
                    Write-Host ""
                    Write-Host "Current: $($selected.Summary)" -ForegroundColor Yellow
                    Write-Host "Enter new name (empty to cancel): " -NoNewline -ForegroundColor Cyan
                    $newName = Read-Host

                    if ($newName -and $newName.Trim().Length -gt 0) {
                        $newName = $newName.Trim()
                        if ($newName.Length -gt 50) {
                            $newName = $newName.Substring(0, 50)
                        }
                        if (-not $sessionNames.sessions) {
                            $sessionNames.sessions = @{}
                        }
                        $sessionNames.sessions.($selected.SessionId) = @{
                            name = $newName
                            updatedAt = (Get-Date).ToString("yyyy-MM-ddTHH:mm:ss")
                            type = "manual"
                        }
                        Save-SessionNames -names $sessionNames
                        $sessions[$selectedIndex].Summary = $newName
                        $sessions[$selectedIndex].HasCustomName = $true
                        Write-Host "Saved!" -ForegroundColor Green
                        Start-Sleep -Milliseconds 500
                    }
                }
            }
        }
    }
}
elseif ($Command -eq "list") {
    Write-Host ""
    $sessions | Select-Object -First 20 | ForEach-Object {
        $star = if ($_.HasCustomName) { "*" } else { " " }
        Write-Host " $star$($_.SessionId.Substring(0,8))... | $($_.Summary)"
    }
}